enhance workflow for build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -23,28 +23,52 @@ jobs:
     steps:
       -
         name: Get remote package data
+        id: tags
         run: |
           set -e -o pipefail
-          latest_tag=$(curl -sSf https://dl-cdn.alpinelinux.org/edge/main/aarch64/APKINDEX.tar.gz |
-            tar -xzO APKINDEX |
-            tr '\n' '\36' |
-            sed -E 's/\o36{2,}/\n/g' |
-            sed -nE '/(^|\o36)P:samba($|\o36)/ s/(^|.+\o36)V:([^\o36]+)($|\o36.+)/\2/ p')
-          echo "Found tag: \"${latest_tag}\"" 
-          latest_version="${latest_tag%-*}"
-          major="${latest_version%%.*}"
-          minor="${latest_version#*.}"
-          minor="${minor%%.*}"
-          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
-          echo "latest_version=$latest_version" >> $GITHUB_ENV
-          echo "latest_minor=$major.$minor" >> $GITHUB_ENV
-          echo "latest_major=$major" >> $GITHUB_ENV
-      - 
+          repo_name="${GITHUB_REPOSITORY##*/}"
+          if [ -z "$repo_name" ]; then
+            echo "ERROR: Unable to determine repository name from GITHUB_REPOSITORY" >&2
+            exit 1
+          fi
+
+          debian_release=$(curl -fsSL https://deb.debian.org/debian/dists/stable/Release)
+          debian_version=$(echo "$debian_release" | awk -F': ' '/^Version:/ {print $2}')
+          debian_codename=$(echo "$debian_release" | awk -F': ' '/^Codename:/ {print $2}')
+          debian_version_major=${debian_version%%.*}
+
+          debian_snapshot=$(curl -fsSL "https://registry.hub.docker.com/v2/repositories/library/debian/tags?page_size=100" |
+            jq -r '.results[].name' |
+            grep "^${debian_codename}-[0-9]\+$" |
+            sort -Vr |
+            head -n1)
+          if [ -z "$debian_snapshot" ]; then
+            echo "No docker snapshot tag found for ${debian_codename}"
+            exit 1
+          fi
+
+          tag=$(curl -fsSL -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            https://api.github.com/repos/${{ github.repository }}/tags?per_page=10 |
+            jq -r '.[].name |
+            select(startswith("v"))' |
+            head -n 1)
+          if [ -z "$tag" ]; then
+            echo "WARNING: No tag found, using 'v0.00' as fallback" >&2
+            tag="v0.0.0"
+          fi
+
+          echo "repo_name=${repo_name}" >> $GITHUB_ENV
+          echo "tag=${tag}" >> $GITHUB_OUTPUT
+          echo "latest_snapshot=${tag}-${debian_snapshot}" >> $GITHUB_OUTPUT
+          echo "latest_version=${tag}-${debian_version}" >> $GITHUB_OUTPUT
+          echo "latest_major=${tag}-${debian_version_major}" >> $GITHUB_OUTPUT
+          echo "latest_codename=${tag}-${debian_codename}" >> $GITHUB_OUTPUT
+      -
         name: Check if the tag exists locally
         uses: action-pack/tag-exists@v1
         id: checkTag
-        with: 
-          tag: 'v${{ env.latest_tag }}'         
+        with:
+          tag: '${{ steps.tags.outputs.latest_snapshot }}'
       -
         name: Finish when found
         run: |
@@ -64,40 +88,33 @@ jobs:
         with:
           context: git
           images: |
-            ${{ secrets.DOCKERHUB_REPO }}
             ghcr.io/${{ github.repository }}
           tags: |
+            type=raw,value=${{ steps.tags.outputs.latest_snapshot }},priority=450
+            type=raw,value=${{ steps.tags.outputs.latest_version }},priority=350
+            type=raw,value=${{ steps.tags.outputs.latest_major }},priority=250
+            type=raw,value=${{ steps.tags.outputs.latest_codename }},priority=150
             type=raw,value=latest,priority=100
-            type=raw,value=${{ env.latest_major }},priority=450
-            type=raw,value=${{ env.latest_minor }},priority=350
-            type=raw,value=${{ env.latest_version }},priority=250
           labels: |
-            org.opencontainers.image.title=${{ vars.NAME }}
+            org.opencontainers.image.title=${{ env.repo_name }}
         env:
           DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
-      - 
-        name: Set up Docker Buildx
-        if: env.exists == 'false'
-        uses: docker/setup-buildx-action@v3
-      -
-        name: Login into Docker Hub
-        if: env.exists == 'false'
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
       -
         name: Login to GitHub Container Registry
         if: env.exists == 'false'
-        uses: docker/login-action@v3
+        uses: docker/login-action@v4
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
       -
+        name: Set up Docker Buildx
+        if: env.exists == 'false'
+        uses: docker/setup-buildx-action@v4
+      -
         name: Build Docker image
         if: env.exists == 'false'
-        uses: docker/build-push-action@v6
+        uses: docker/build-push-action@v7
         with:
           context: .
           push: true
@@ -107,25 +124,4 @@ jobs:
           labels: ${{ steps.meta.outputs.labels }}
           annotations: ${{ steps.meta.outputs.annotations }}
           build-args: |
-            VERSION_ARG=${{ env.latest_version }}
-      -
-        name: Create a release
-        if: env.exists == 'false'
-        uses: action-pack/github-release@v2
-        with:
-          tag: "v${{ env.latest_tag }}"
-          title: "v${{ env.latest_version }}"
-          token: ${{ secrets.REPO_ACCESS_TOKEN }}
-      -
-        name: Send mail
-        if: env.exists == 'false'
-        uses: action-pack/send-mail@v1
-        with:
-          to: ${{secrets.MAILTO}}
-          from: Github Actions <${{secrets.MAILTO}}>
-          connection_url: ${{secrets.MAIL_CONNECTION}}
-          subject: Build of ${{ github.event.repository.name }} v${{ env.latest_tag }} completed
-          body: |
-              The build job of ${{ github.event.repository.name }} v${{ env.latest_tag }} was completed successfully! 
-              
-              See https://github.com/${{ github.repository }}/actions for more information.
+            VERSION_ARG=${{ steps.tags.outputs.latest_snapshot }}
